apiVersion: v1
kind: Template
parameters:
- name: WEBHOOK_NAME
  required: true
  description: Name of webhook to deploy
- name: IMAGE_TAG
  required: true
  description: Image tag to assign to built webhook image
  value: latest
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: ${WEBHOOK_NAME}-serving-cert
    labels:
      webhook: ${WEBHOOK_NAME}
    name: ${WEBHOOK_NAME}
  spec:
    ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      webhook: ${WEBHOOK_NAME}
      deploymentconfig: ${WEBHOOK_NAME}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      webhook: ${WEBHOOK_NAME}
    name: ${WEBHOOK_NAME}
  spec:
    replicas: 1
    selector:
      webhook: ${WEBHOOK_NAME}
      deploymentconfig: ${WEBHOOK_NAME}
    template:
      metadata:
        labels:
          webhook: ${WEBHOOK_NAME}
          deploymentconfig: ${WEBHOOK_NAME}
      spec:
        containers:
        - name: ${WEBHOOK_NAME}
          image: ${WEBHOOK_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          volumeMounts:
          - mountPath: /tls
            name: serving-cert
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: ${WEBHOOK_NAME}-serving-cert
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${WEBHOOK_NAME}
        from:
          kind: ImageStreamTag
          name: ${WEBHOOK_NAME}:latest
          